const fs = require('fs');
const path = require('path');

const prismaDir = path.resolve('src/fixed-prisma');
const indexPath = path.join(prismaDir, 'index.js');

const DMMF = {
  "models": {
    "Voice": {
      "fields": [
        {"name":"id","kind":"scalar","type":"String"}, {"name":"orgId","kind":"scalar","type":"String"},
        {"name":"name","kind":"scalar","type":"String"}, {"name":"provider","kind":"enum","type":"Provider"}
      ]
    },
    "Generation": {
      "fields": [
        {"name":"id","kind":"scalar","type":"String"}, {"name":"orgId","kind":"scalar","type":"String"},
        {"name":"provider","kind":"enum","type":"Provider"}, {"name":"model","kind":"scalar","type":"String"},
        {"name":"pace","kind":"scalar","type":"Float"}, {"name":"language","kind":"scalar","type":"String"}
      ]
    }
  },
  "enums": {
    "Provider": { "values": [{ "name": "MODAL", "dbName": null }, { "name": "SARVAM", "dbName": null }] }
  }
};

const dmmfStr = JSON.stringify(DMMF);

const minimalSchema = `
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

enum Provider {
  MODAL
  SARVAM
}

model Voice {
  id String @id
  orgId String?
  name String
  provider Provider @default(MODAL)
}

model Generation {
  id String @id
  orgId String
  provider Provider @default(MODAL)
  model String?
  pace Float?
  language String?
}
`;

const escapedSchema = JSON.stringify(minimalSchema).slice(1, -1);

const INDEX_JS = "/* !!! This is code generated by Prisma. Do not edit directly. !!! */\n" +
"Object.defineProperty(exports, \"__esModule\", { value: true });\n" +
"const { getPrismaClient, defineDmmfProperty, makeStrictEnum } = require('./runtime/client.js');\n" +
"const Prisma = {}; exports.Prisma = Prisma; exports.$Enums = {};\n" +
"Prisma.prismaVersion = { client: \"7.4.1\", engine: \"55ae170b1ced7fc6ed07a15f110549408c501bb3\" };\n" +
"exports.Prisma.VoiceScalarFieldEnum = { id: 'id', orgId: 'orgId', name: 'name', provider: 'provider' };\n" +
"exports.Prisma.GenerationScalarFieldEnum = { id: 'id', orgId: 'orgId', provider: 'provider', model: 'model', pace: 'pace', language: 'language' };\n" +
"exports.VoiceVariant = exports.$Enums.VoiceVariant = { SYSTEM: 'SYSTEM', CUSTOM: 'CUSTOM' };\n" +
"exports.Provider = exports.$Enums.Provider = { MODAL: 'MODAL', SARVAM: 'SARVAM' };\n" +
"exports.VoiceCategory = exports.$Enums.VoiceCategory = { GENERAL: 'GENERAL' };\n" +
"const config = {\n" +
"  \"previewFeatures\": [], \"clientVersion\": \"7.4.1\", \"activeProvider\": \"postgresql\",\n" +
"  \"inlineSchema\": \"" + escapedSchema + "\", \"runtimeDataModel\": " + dmmfStr + ",\n" +
"  \"parameterizationSchema\": null\n" +
"};\n" +
"defineDmmfProperty(exports.Prisma, config.runtimeDataModel);\n" +
"exports.PrismaClient = getPrismaClient(config);\n" +
"Object.assign(exports, Prisma);\n";

fs.writeFileSync(indexPath, INDEX_JS, 'utf8');
console.log('RECONSTRUCTED Shadow Index with minimal inlineSchema.');
