/* !!! This is code generated by Prisma. Do not edit directly. !!! */
import * as runtime from "@prisma/client/runtime/client";

const DMMF = {
  "models": {
    "Voice": {
      "fields": [
        {"name":"id","kind":"scalar","type":"String"},
        {"name":"orgId","kind":"scalar","type":"String"},
        {"name":"name","kind":"scalar","type":"String"},
        {"name":"provider","kind":"enum","type":"Provider"}
      ]
    },
    "Generation": {
      "fields": [
        {"name":"id","kind":"scalar","type":"String"},
        {"name":"orgId","kind":"scalar","type":"String"},
        {"name":"provider","kind":"enum","type":"Provider"},
        {"name":"model","kind":"scalar","type":"String"},
        {"name":"pace","kind":"scalar","type":"Float"},
        {"name":"language","kind":"scalar","type":"String"}
      ]
    }
  },
  "enums": {
    "Provider": { "values": [{ "name": "MODAL", "dbName": null }, { "name": "SARVAM", "dbName": null }] }
  }
};

const config: any = {
  "previewFeatures": [],
  "clientVersion": "7.4.1",
  "activeProvider": "postgresql",
  "inlineSchema": "",
  "runtimeDataModel": DMMF,
  "parameterizationSchema": null
};

export function getPrismaClientClass() {
  return runtime.getPrismaClient(config);
}
