/* !!! This is code generated by Prisma. Do not edit directly. !!! */

Object.defineProperty(exports, "__esModule", { value: true });

const { makeStrictEnum } = require('./runtime/client.js');

exports.VoiceVariant = {
  SYSTEM: 'SYSTEM',
  CUSTOM: 'CUSTOM'
};

exports.Provider = {
  MODAL: 'MODAL',
  SARVAM: 'SARVAM'
};

exports.VoiceCategory = {
  AUDIOBOOK: 'AUDIOBOOK',
  CONVERSATIONAL: 'CONVERSATIONAL',
  CUSTOMER_SERVICE: 'CUSTOMER_SERVICE',
  GENERAL: 'GENERAL',
  NARRATIVE: 'NARRATIVE',
  CHARACTERS: 'CHARACTERS',
  MEDITATION: 'MEDITATION',
  MOTIVATIONAL: 'MOTIVATIONAL',
  PODCAST: 'PODCAST',
  ADVERTISING: 'ADVERTISING',
  VOICEOVER: 'VOICEOVER',
  CORPORATE: 'CORPORATE'
};
