/* !!! This is code generated by Prisma. Do not edit directly. !!! */
Object.defineProperty(exports, "__esModule", { value: true });
const { getPrismaClient, defineDmmfProperty, makeStrictEnum } = require('./runtime/client.js');
const Prisma = {}; exports.Prisma = Prisma; exports.$Enums = {};
Prisma.prismaVersion = { client: "7.4.1", engine: "55ae170b1ced7fc6ed07a15f110549408c501bb3" };
exports.Prisma.VoiceScalarFieldEnum = { id: 'id', orgId: 'orgId', name: 'name', provider: 'provider' };
exports.Prisma.GenerationScalarFieldEnum = { id: 'id', orgId: 'orgId', provider: 'provider', model: 'model', pace: 'pace', language: 'language' };
exports.VoiceVariant = exports.$Enums.VoiceVariant = { SYSTEM: 'SYSTEM', CUSTOM: 'CUSTOM' };
exports.Provider = exports.$Enums.Provider = { MODAL: 'MODAL', SARVAM: 'SARVAM' };
exports.VoiceCategory = exports.$Enums.VoiceCategory = { GENERAL: 'GENERAL' };
const config = {
  "previewFeatures": [], "clientVersion": "7.4.1", "activeProvider": "postgresql",
  "inlineSchema": "\ngenerator client {\n  provider = \"prisma-client-js\"\n}\n\ndatasource db {\n  provider = \"postgresql\"\n  url      = env(\"DATABASE_URL\")\n}\n\nenum Provider {\n  MODAL\n  SARVAM\n}\n\nmodel Voice {\n  id String @id\n  orgId String?\n  name String\n  provider Provider @default(MODAL)\n}\n\nmodel Generation {\n  id String @id\n  orgId String\n  provider Provider @default(MODAL)\n  model String?\n  pace Float?\n  language String?\n}\n", "runtimeDataModel": {"models":{"Voice":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"orgId","kind":"scalar","type":"String"},{"name":"name","kind":"scalar","type":"String"},{"name":"provider","kind":"enum","type":"Provider"}]},"Generation":{"fields":[{"name":"id","kind":"scalar","type":"String"},{"name":"orgId","kind":"scalar","type":"String"},{"name":"provider","kind":"enum","type":"Provider"},{"name":"model","kind":"scalar","type":"String"},{"name":"pace","kind":"scalar","type":"Float"},{"name":"language","kind":"scalar","type":"String"}]}},"enums":{"Provider":{"values":[{"name":"MODAL","dbName":null},{"name":"SARVAM","dbName":null}]}}},
  "parameterizationSchema": null
};
defineDmmfProperty(exports.Prisma, config.runtimeDataModel);
exports.PrismaClient = getPrismaClient(config);
Object.assign(exports, Prisma);
